### ISSUE TITLE
Add headlineAspectRatio into remember param list

### ISSUE THREAD

**Issue by oxyroid** [oxyroid/M3UAndroid#171]
https://github.com/oxyroid/M3UAndroid/blob/fb595620d720b6e62ced403c2dab30a71405bd2b/feature/foryou/src/main/java/com/m3u/feature/foryou/components/PlaylistGallery.kt#L81

**Comment by oxyroid** [comment]
name = 1.14.0-rc01-snapshot[06160733]
code = 141
BOARD = kalama
BOOTLOADER = unknown
BRAND = OnePlus
CPU_ABI = arm64-v8a
CPU_ABI2 = 
DEVICE = OP5CF9L1
DISPLAY = PJE110_14.0.0.505(CN01)
FINGERPRINT = OnePlus/PJE110/OP5CF9L1:14/TP1A.220905.001/U.173ebf9-1-99b0a:user/release-keys
HARDWARE = qcom
HOST = dg02-pool06-kvm45
ID = TP1A.220905.001
IS_DEBUGGABLE = false
IS_EMULATOR = false
MANUFACTURER = OnePlus
MODEL = PJE110
ODM_SKU = 7
PERMISSIONS_REVIEW_REQUIRED = true
PRODUCT = PJE110
RADIO = unknown
SERIAL = unknown
SKU = unknown
SOC_MANUFACTURER = QTI
SOC_MODEL = SM8550
SUPPORTED_32_BIT_ABIS = [Ljava.lang.String;@4c85e58
SUPPORTED_64_BIT_ABIS = [Ljava.lang.String;@61f2bb1
SUPPORTED_ABIS = [Ljava.lang.String;@67bb896
TAGS = release-keys
TIME = 1711463614000
TYPE = user
UNKNOWN = unknown
USER = root

java.lang.IllegalArgumentException: maxWidth(-123) must be >= than minWidth(0)
	at qg.l0.h2(Unknown Source:2)
	at k1.a.a(Unknown Source:116)
	at k1.a.b(Unknown Source:14)
	at h2.b0.c(Unknown Source:13)
	at h2.c0.V(Unknown Source:11)
	at h2.n0.V(Unknown Source:9)
	at r0.c2.d(Unknown Source:124)
	at f2.z0.d(Unknown Source:6)
	at h2.x.w(Unknown Source:37)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at androidx.compose.foundation.layout.a.o(Unknown Source:123)
	at x.b0.d(Unknown Source:45)
	at h2.x.w(Unknown Source:37)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x.u1.f(Unknown Source:114)
	at h2.c0.w(Unknown Source:14)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:113)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at a0.g0.b(Unknown Source:55)
	at z.b0.a(Unknown Source:22)
	at z.u.b(Unknown Source:64)
	at qg.l0.H1(Unknown Source:293)
	at z.v.invoke(Unknown Source:640)
	at a0.y.invoke(Unknown Source:271)
	at f2.h0.d(Unknown Source:79)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:218)
	at h2.x.w(Unknown Source:37)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at q.y.d(Unknown Source:23)
	at h2.x.w(Unknown Source:37)
	at q.a1.f(Unknown Source:240)
	at h2.c0.w(Unknown Source:14)
	at r1.q.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at q.h.c(Unknown Source:120)
	at q.h.invoke(Unknown Source:256)
	at f2.b0.f(Unknown Source:7)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at q.p.d(Unknown Source:57)
	at h2.x.w(Unknown Source:37)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:218)
	at h2.x.w(Unknown Source:37)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at q.h0.invoke(Unknown Source:914)
	at f2.h0.d(Unknown Source:79)
	at h2.x.w(Unknown Source:37)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at oc.j0.invoke(Unknown Source:339)
	at f2.h0.d(Unknown Source:79)
	at h2.x.w(Unknown Source:37)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at x.k0.f(Unknown Source:96)
	at h2.c0.w(Unknown Source:14)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:55)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.n0.w(Unknown Source:90)
	at x.w.d(Unknown Source:111)
	at h2.x.w(Unknown Source:37)
	at r1.w0.f(Unknown Source:0)
	at h2.c0.w(Unknown Source:14)
	at x1.c0.invoke(SourceFile:223)
	at x1.c0.invoke(SourceFile:188)
	at t0.u.i(Unknown Source:113)
	at i1.v.a(Unknown Source:53)
	at i1.w.d(Unknown Source:132)
	at h2.t1.a(Unknown Source:2)
	at h2.n0.F0(Unknown Source:109)
	at h2.h0.N(Unknown Source:16)
	at h2.h0.O(Unknown Source:17)
	at h2.v0.c(Unknown Source:7)
	at h2.v0.m(Unknown Source:137)
	at h2.v0.g(Unknown Source:93)
	at h2.v0.f(Unknown Source:39)
	at h2.n0.F0(Unknown Source:57)
	at h2.h0.N(Unknown Source:16)
	at h2.v0.c(Unknown Source:2)
	at h2.v0.o(Unknown Source:22)
	at h2.v0.l(Unknown Source:61)
	at i2.c0.onMeasure(Unknown Source:82)
	at android.view.View.measure(View.java:27548)
	at i2.a.g(Unknown Source:63)
	at i2.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7123)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7123)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7123)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7123)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7123)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:824)
	at android.view.View.measure(View.java:27548)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4646)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3070)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3433)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2741)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10184)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1544)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
	at android.view.Choreographer.doFrame(Choreographer.java:994)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by oxyroid** [comment]
Under the 1.14.0-rc01 release build and keep the colorful background off, if there are recommend items in foryou page. Once we rotate the screen, the app will crash.

Not sure it will be reproduced under the debug build.
